[project]
name = "starbun"
version = "0.1.0"
description = "A tool for finding out things about nuclear reactors."

[build-system]
build-backend = "flit_core.buildapi"
requires = ["flit_core >=3.2,<4"]